### ISSUE TITLE
Feature request: comments

### ISSUE THREAD

**Issue by eater** [parnold-x/nasc#34]
When doing calculations, it would be very useful for the user to be able to add comments at the end of a line in the input area, to be able to keep track of what exactly he or she is calculating. The comments would be ignored by the calculator.

I can imagine this could be implemented with a symbol such as `"` or `//` that's not otherwise used. So it might look like

```
1156         // daily requirement
7 * 166        // number of days
line1 * line2    // total requirement!
```

**Comment by parnold-x** [comment]
That remindes me that originally i wanted to add some smart decision mechanism. The decision what can be calculated and what not is at the moment per line. It would also be possible to futher split that up, so that it extracts the calulcations from a line and only calculates what can be calculated. 
Either way the comments can be a handy to also visualize as comment. So will proably add that when I have time.

**Comment by parnold-x** [comment]
Added

**Comment by parnold-x** [comment]
Super. I Don't think so that these comments should be in the result view.
