### ISSUE TITLE
Percentage not working correctly

### ISSUE THREAD

**Issue by danigamba** [parnold-x/nasc#58]
When i try to sum or subtract a percentage it just sum the zero dotted value to the first number.
As an example, if i do
`100 - 30% = 99.7`
instead of `70` as i was expecting
I'm using the 0.4.3 version.

**Comment by parnold-x** [comment]
Actually it is working correctly in a mathematical sense.
The issue is that the context (base value) of the 30 % is not 100.
So your equation means 100 - (30% * 1) = 100 - 0,3 = 99,7

I know that some calculators handle this special case. The calculator lib that I use ([libqualculate](https://github.com/Qalculate/libqalculate/issues)) does not. So either libqualculate will handle this or I NaSC must add some special case handling, which I will not do because this will introduce propably a lot of issues in other math parts. Sorry and thanks for the report.

**Comment by danigamba** [comment]
Okok, thanks for the explanation
