### ISSUE TITLE
Accessing sheets

### ISSUE THREAD

**Issue by phw** [parnold-x/nasc#72]
I can add a new sheet with the `Ctrl+N` shortcut, but so far I don't see any visible way to access my previous sheets. The source code suggest there is a footer toolbar. Is this not yet implemented or is it a bug that I can't see it?

Running on Arch Linux, built from source.

**Comment by parnold-x** [comment]
There was a whole managment pane where you can load/save and manage the sheets. But the loading is bugged for this because some strange thread issues. Like I said some parts need to be rewritten. 
Quickfix was to just remove the functionality. So at the moment this is intended.

**Comment by julientaq** [comment]
back on this.
I want to use Nasc as my only maths tools because it's an awesome tool, but if i can't save my sheets, i must copy the content in another text file and this is quite a pain.
What are those `some strange thread issues` you're talking about @parnold-x ?  What exactly happens?

Thanks for the good app you're building though :)

**Comment by julientaq** [comment]
hey @parnold-x.
Any update on that one?

i really can't use the app  (which i love) on a daily basis :(

**Comment by ozel** [comment]
I tried to find the associated commit that @parnold-x mentioned which supposedly removed the saving/loading pane. No luck so far with using a couple of different keywords in order to find it in the commits. I'd be willing to learn vala for this, just because the program is so nice and useful for me, too. Even though I can imagine the thread issue is probably not an easy one to solve...
Any pointers where to start?

**Comment by parnold-x** [comment]
@ozel 
It was this commit on launchpad. Should be easy to readd except for the thread issue.
https://bazaar.launchpad.net/~nasc-team/nasc/trunk/revision/79

**Comment by parnold-x** [comment]
Sheet managing pane is available now
